#!/usr/bin/env ruby



case RUBY_PLATFORM
when 'java'

wXfbase = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
WXFDIR = File.join(File.expand_path(File.dirname(wXfbase)))
$:.unshift(File.join(File.expand_path(File.dirname(wXfbase)), 'jlib'))

 require 'rubygems'
 require 'optparse'
 
 begin 
 	require 'openssl'
 rescue LoadError
 	print("\e[1;31m[wXf error]\e[0m Please run: $ sudo gem install jruby-openssl\n")
 	exit
 end


class OptsParse

  def self.parse(cmds)
    options = {}
    OptionParser.new do |opt|
      
      opt.on("-b", "-b <burp.jar>", "Load the specified burp jar file") do |b|
	    options['Burp'] = b
	  end  
	  
	  opt.on("-r", "-r <save_state>", "Load the specified save state file") do |r|
	    options['Restore'] = r
	  end  
	
	
	  opt.on_tail("-h", "--help", "Show this message") do
        puts opt
        exit
      end
        
	  begin
	    opt.parse!(cmds)
	  rescue OptionParser::InvalidOption
        puts "\e[1;31m[wXf error]\e[0m Invalid option, try -h for usage"
        exit
      rescue OptionParser::MissingArgument
        puts "\e[1;31m[wXf error]\e[0m You are missing an argument"
        exit
	  end
	
	end
   options
  end
    
end

options = OptsParse.parse(ARGV)

begin
 require 'buby'
rescue LoadError
 print("\e[1;31m[wXf error]\e[0m Please install buby: sudo jruby -S gem install buby\n")
 exit
end

require 'wXf/wXfassists'
require 'wXf/wXfconductors'
require 'wXf/wXfdb'
require 'wXf/wXfconstants'
require 'wXf/wXflog'
require 'wXf/wXfmod_factory'
require 'wXf/wXfui'
require 'wXf/wXfwebserver'

begin
WXf::WXfui::Console::Operations::Control.new("wXf", "//>", options).start
rescue Interrupt		
end

else

require 'rubygems'
require 'optparse'
 

class OptsParse

  def self.parse(cmds)
    options = {}
    OptionParser.new do |opt|
	
	  opt.on_tail("-h", "--help", "Show this message") do
        puts opt
        exit
      end
        
	  begin
	    opt.parse!(cmds)
	  rescue OptionParser::InvalidOption
        puts "\e[1;31m[wXf error]\e[0m Invalid option, try -h for usage"
        exit
      rescue OptionParser::MissingArgument
        puts "\e[1;31m[wXf error]\e[0m You are missing an argument"
        exit
	  end
	
	end
   options
  end
    
end

options = OptsParse.parse(ARGV)


wXfbase = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
WXFDIR = File.join(File.expand_path(File.dirname(wXfbase)))
$:.unshift(File.join(File.expand_path(File.dirname(wXfbase)), 'lib'))

require 'wXf/wXfassists'
require 'wXf/wXfconductors'
require 'wXf/wXfdb'
require 'wXf/wXfconstants'
require 'wXf/wXflog'
require 'wXf/wXfmod_factory'
require 'wXf/wXfui'
require 'wXf/wXfwebserver'
require 'wXf/wXfxmlrpc'


begin
WXf::WXfui::Console::Operations::Control.new("wXf", "//>", options ).start
rescue Interrupt		
end
end
