require 'wXfgui/analysis/panels/analysis_panel'
require 'wXfgui/analysis/panels/dt_analysis_panel'
require 'wXfgui/analysis/panels/details_panel'
require 'wXfgui/analysis/panels/info_panel'
require 'wXfgui/analysis/panels/dt_table_panel'
