require 'wXf/wXfui/console/processing/aux_procs'
require 'wXf/wXfui/console/processing/buby_procs'
require 'wXf/wXfui/console/processing/burp_procs'
require 'wXf/wXfui/console/processing/core_procs'
require 'wXf/wXfui/console/processing/exploit_procs'
require 'wXf/wXfui/console/processing/webserver_procs'